import { sourceGroundingReviewInputSchema, type SourceAnswerScope } from "@interview/schemas";

// Paired replay cases derived from synthetic QA ac5fa67 diagnostics (2026-09-05).
// Expected verdicts distinguish semantic support from wording similarity.
const nubeqaSafety = "General safety guidance includes monitoring ischemic heart disease symptoms and managing cardiovascular risk factors, including hypertension, diabetes, and dyslipidemia; discontinue NUBEQA for Grade 3-4 ischemic heart disease. These are general NUBEQA warnings, not evidence that a particular interacting medicine causes ischemic heart disease or seizure.";
const nubeqaInteraction = "Combined P-gp and strong CYP3A4 inhibitors increase darolutamide exposure; the label calls for more frequent monitoring for NUBEQA adverse reactions and dosage modification as needed.";
const brukinsaInteraction = "Moderate or strong CYP3A inhibitors increase zanubrutinib exposure (Cmax and AUC), which may increase BRUKINSA toxicity risk; the label calls for reducing the BRUKINSA dose during coadministration. Table 17 provides these interaction effects and management instructions, without incidence rates for individual adverse reactions attributable to these combinations.";
const brukinsaSafety = "Practical guidance includes checking for bleeding or infection symptoms and monitoring complete blood counts during treatment. These are general treatment precautions; they do not establish which individual adverse reactions result from a specific drug interaction.";
const padcevChecklist = "Source notes: Checklist is a guide to help HCPs identify or monitor any potential adverse reactions that may occur during PADCEV treatment prior to each infusion and follow-up. It prompts review of signs and questions for skin reactions; hyperglycemia; pneumonitis/ILD; peripheral neuropathy; ocular disorders; infusion site extravasation; GI symptoms including nausea, vomiting, diarrhea, constipation, abdominal pain; and follow-up actions. Use as an HCP monitoring workflow supplement; PI remains controlling label source.";

const genericScope: SourceAnswerScope = { version: 1, currentParticipantRequest: "Explain the supplied information.", resolvedSourceQuestion: null, sourceTopicContext: null, sourceQuestionPlan: null, presentationPlan: null };
const pfsScope: SourceAnswerScope = { ...genericScope, currentParticipantRequest: "I want to understand PFS and DDI.", resolvedSourceQuestion: "What progression-free survival results are described?", presentationPlan: { version: 1, purpose: "source_answer", depth: "brief", maxFacts: 3, maxTopics: 1, askReadiness: false } };
const scopeSources = ["Trial A reports radiographic progression-free survival (rPFS) as its primary endpoint in population A.", "Trial B reports metastasis-free survival (MFS) as its primary endpoint in population B."];
const scopedComparison = "Trial A reports rPFS in population A. [1] Trial B reports MFS in population B. [2]";
// Brand-neutral synthetic evidence isolates enumeration from exhaustive claims.
const enumerationSources = ["Trial A reports PFS for Drug X in previously untreated advanced disease.", "Trial B reports PFS for Drug X in advanced disease after prior platinum-based therapy."];
const enumerationDetails = "Trial A studied previously untreated advanced disease. [1] Trial B studied advanced disease after prior platinum-based therapy. [2]";

function fixture(id: string, text: string, sources: string[], unsupported: { excerpt: string; reason: string } | null, answerScope: SourceAnswerScope = genericScope) {
  return {
    id,
    input: sourceGroundingReviewInputSchema.parse({ draft: { practicalAnswer: text, qualification: null }, sources: sources.map((source, index) => ({ index: index + 1, text: source })), answerScope }),
    expected: { version: 1 as const, supported: unsupported === null, unsupportedClaims: unsupported ? [unsupported] : [] },
  };
}

export const sourceGroundingCalibrationFixtures = [
  fixture("supported_settings_enumeration_is_not_exhaustive", `PFS has been reported for Drug X in two advanced-disease settings. [1] [2] ${enumerationDetails}`, enumerationSources, null, pfsScope),
  fixture("explicit_only_settings_requires_exhaustive_support", `PFS has been reported for Drug X only in these two advanced-disease settings. [1] [2] ${enumerationDetails}`, enumerationSources, { excerpt: "only in these two advanced-disease settings", reason: "Two supplied study settings do not establish that PFS has never been reported in any other setting." }, pfsScope),
  fixture("explicit_all_settings_requires_exhaustive_support", `These are all settings in which PFS has been reported for Drug X. [1] [2] ${enumerationDetails}`, enumerationSources, { excerpt: "all settings in which PFS has been reported for Drug X", reason: "The supplied studies do not establish a complete inventory of every reported setting." }, pfsScope),
  fixture("enumeration_must_preserve_prior_therapy_setting", "PFS has been reported for Drug X in two advanced-disease settings. [1] [2] Trial A studied previously untreated advanced disease. [1] Trial B reports PFS for patients with advanced disease regardless of prior therapy. [2]", enumerationSources, { excerpt: "regardless of prior therapy", reason: "Trial B is limited to advanced disease after prior platinum-based therapy; the draft removes that applicability condition." }, pfsScope),
  fixture("enumeration_omitted_prior_therapy_qualifier", "PFS has been reported for Drug X in two advanced-disease settings. [1] [2] Trial A studied previously untreated advanced disease. [1] Trial B reports PFS for patients with advanced disease. [2]", enumerationSources, { excerpt: "Trial B reports PFS for patients with advanced disease. [2]", reason: "The Trial B setting omits the necessary after-prior-platinum-based-therapy qualifier and therefore broadens its applicability." }, pfsScope),
  fixture("same_source_unasked_incidence_gap_is_off_scope", "The source describes interaction management. [1] This provided excerpt does not report adverse-reaction incidence rates. [1]", ["The source describes interaction management. This excerpt does not report adverse-reaction incidence rates."], { excerpt: "This provided excerpt does not report adverse-reaction incidence rates. [1]", reason: "The participant requested interaction information, not an inventory of missing incidence data; the aside is unnecessary to interpret the answer." }, { ...genericScope, currentParticipantRequest: "What interactions are described?", resolvedSourceQuestion: "What interactions are described?" }),
  fixture("explicit_incidence_question_allows_bounded_gap", "This provided excerpt does not report adverse-reaction incidence rates. [1]", ["The source describes interaction management. This excerpt does not report adverse-reaction incidence rates."], null, { ...genericScope, currentParticipantRequest: "What adverse-reaction incidence rates does this excerpt report?", resolvedSourceQuestion: "What adverse-reaction incidence rates does this excerpt report?" }),
  fixture("single_point_scope_rejects_second_independent_case", "With combined P-gp and strong CYP3A4 inhibitors, monitor more often for NUBEQA adverse reactions. [1] Separately, general safety guidance includes monitoring ischemic heart disease symptoms. [2]", [nubeqaInteraction, nubeqaSafety], { excerpt: "Separately, general safety guidance includes monitoring ischemic heart disease symptoms. [2]", reason: "This second independent monitoring point exceeds the selected one-point simplification; retain the first complete conditional instruction." }, { ...genericScope, currentParticipantRequest: "Even more simply please.", resolvedSourceQuestion: "Explain interaction monitoring and separate general safety guidance.", presentationPlan: { version: 1, purpose: "source_answer", depth: "brief", maxFacts: 1, maxTopics: 1, maxWords: 40, askReadiness: false } }),
  fixture("pfs_scope_rejects_unsolicited_mfs_contrast", scopedComparison, scopeSources, { excerpt: "Trial B reports MFS in population B. [2]", reason: "This MFS/population contrast is outside the selected PFS information need; remove the unsolicited comparison." }, pfsScope),
  fixture("explicit_endpoint_comparison_permits_separate_settings", scopedComparison, scopeSources, null, { ...pfsScope, currentParticipantRequest: "Compare the PFS and MFS endpoints and their populations.", resolvedSourceQuestion: "Compare the PFS and MFS endpoints and their populations." }),
  fixture("pfs_scope_keeps_essential_endpoint_population_qualifiers", "Trial A reports radiographic progression-free survival (rPFS) in population A. [1]", scopeSources, null, pfsScope),
  fixture("selected_priority_not_entire_participant_list", "Trial A reports rPFS in population A. [1] The interaction source reports an exposure change. [2]", [scopeSources[0], "The interaction source reports an exposure change."], { excerpt: "The interaction source reports an exposure change. [2]", reason: "DDI is a separately listed priority, not the application-selected PFS information need for this turn." }, pfsScope),
  fixture("practical_context_accepts_general_monitoring", "Separately, general NUBEQA safety guidance includes monitoring ischemic heart disease symptoms. [1]", [nubeqaSafety], null, { ...genericScope, currentParticipantRequest: "What does that mean for what to monitor in practical terms?", resolvedSourceQuestion: "What general safety information helps explain the monitoring discussion?", sourceTopicContext: "Drug interaction monitoring", sourceQuestionPlan: { version: 1, interpretedQuestion: "Explain practical monitoring with separately identified general safety guidance.", retrievalQueries: ["interaction monitoring", "general safety"], usesSourceContext: true, answerApproach: "contextual_explanation", contextBoundary: "Do not imply interaction-specific causation.", rationale: "Requested practical context." } }),
  fixture("one_fact_simplification_does_not_require_all_prior_cases", "General NUBEQA safety guidance includes monitoring ischemic heart disease symptoms. [1]", [nubeqaSafety, nubeqaInteraction], null, { ...genericScope, currentParticipantRequest: "Even more simply please.", resolvedSourceQuestion: "Explain interaction monitoring and separate general safety guidance.", sourceTopicContext: "Practical monitoring", presentationPlan: { version: 1, purpose: "source_answer", depth: "brief", maxFacts: 1, maxTopics: 1, maxWords: 40, askReadiness: false } }),
  fixture("verifiable_excerpt_omission", "This provided interaction excerpt does not name particular NUBEQA adverse reactions to watch for with combined P-gp and strong CYP3A4 inhibitors. [1]", [nubeqaInteraction], null),
  fixture("excerpt_omission_is_not_label_omission", "The NUBEQA label does not name particular adverse reactions to watch for with combined P-gp and strong CYP3A4 inhibitors. [1]", [nubeqaInteraction], { excerpt: "The NUBEQA label does not name particular adverse reactions", reason: "This selected excerpt cannot establish what is absent from the complete label." }),
  fixture("excerpt_omission_cannot_ignore_named_events", "This provided excerpt does not name particular reactions to watch for. [1]", [nubeqaSafety], { excerpt: "does not name particular reactions to watch for", reason: "The excerpt explicitly identifies monitoring ischemic heart disease symptoms." }),
  fixture("defined_toxicity_threshold_preserved", "For Grade 3 or greater toxicity or an intolerable adverse reaction, treatment may be withheld or reduced to 300 mg twice daily until symptoms improve. [1]", ["For Grade 3 or greater toxicity or an intolerable adverse reaction, withhold treatment or reduce to 300 mg twice daily until symptoms improve."], null),
  fixture("passive_voice_preserves_management", "For Grade 3 or greater toxicity or an intolerable adverse reaction, treatment should be withheld or reduced to 300 mg twice daily until symptoms improve. [1]", ["For Grade 3 or greater toxicity or an intolerable adverse reaction, withhold treatment or reduce to 300 mg twice daily until symptoms improve."], null),
  fixture("management_condition_removed", "Treatment should be withheld or reduced to 300 mg twice daily for any adverse reaction. [1]", ["For Grade 3 or greater toxicity or an intolerable adverse reaction, withhold treatment or reduce to 300 mg twice daily until symptoms improve."], { excerpt: "for any adverse reaction", reason: "The source limits this management instruction to Grade 3 or greater toxicity or an intolerable adverse reaction." }),
  fixture("unambiguous_substrate_antecedent", "If a BCRP substrate is used with NUBEQA, the label advises monitoring for adverse reactions from that substrate drug and considering its dose reduction. [1]", ["NUBEQA inhibits BCRP and can increase exposure to its substrates. The label advises avoiding BCRP substrates where possible; if used together, monitor for adverse reactions and consider substrate dose reduction."], null),
  fixture("substrate_instruction_switched_to_nubeqa", "If a BCRP substrate is used with NUBEQA, the label advises monitoring for NUBEQA adverse reactions and considering NUBEQA dose reduction. [1]", ["NUBEQA inhibits BCRP and can increase exposure to its substrates. The label advises avoiding BCRP substrates where possible; if used together, monitor for adverse reactions and consider substrate dose reduction."], { excerpt: "monitoring for NUBEQA adverse reactions and considering NUBEQA dose reduction", reason: "The source instruction concerns the substrate drug, not NUBEQA." }),
  fixture("increased_monitoring_plain_language", "With combined P-gp and strong CYP3A4 inhibitors, the label says to watch more closely for NUBEQA adverse reactions. [1]", [nubeqaInteraction], null),
  fixture("counseling_remains_counseling", "General NUBEQA safety guidance advises counseling patients about seizure risk. [1]", ["Counsel patients about seizure risk and activities where loss of consciousness could cause harm."], null),
  fixture("counseling_is_not_monitoring", "General NUBEQA safety guidance advises monitoring seizure risk. [1]", ["Counsel patients about seizure risk and activities where loss of consciousness could cause harm."], { excerpt: "monitoring seizure risk", reason: "The source directs counseling about the risk, not monitoring that risk." }),
  fixture("management_is_not_screening", "The label directs screening for Grade 3 toxicity. [1]", ["For Grade 3 or greater toxicity or an intolerable adverse reaction, withhold treatment or reduce to 300 mg twice daily until symptoms improve."], { excerpt: "directs screening for Grade 3 toxicity", reason: "This is a management threshold after toxicity develops, not a screening instruction." }),
  fixture("faithful_watch_monitor_paraphrase", "General NUBEQA safety guidance includes watching for ischemic heart disease symptoms. [1]", [nubeqaSafety], null),
  fixture("invented_weekly_frequency", "General NUBEQA safety guidance calls for weekly checks for ischemic heart disease symptoms. [1]", [nubeqaSafety], { excerpt: "weekly checks", reason: "The source gives no weekly frequency." }),
  fixture("attributed_checklist_without_boilerplate", "As general PADCEV monitoring workflow guidance, the checklist prompts review before each infusion and follow-up for skin reactions, hyperglycemia, pneumonitis or ILD, and peripheral neuropathy. [1]", [padcevChecklist], null),
  fixture("checklist_falsely_called_label", "The PADCEV prescribing information requires reviewing skin reactions before each infusion and follow-up. [1]", [padcevChecklist], { excerpt: "The PADCEV prescribing information requires", reason: "This is a checklist prompt, not evidence of a prescribing-information requirement." }),
  fixture("independent_general_safety_context", "The label calls for reducing BRUKINSA dose with moderate or strong CYP3A inhibitors. [1] Separately, general safety guidance includes checking for bleeding or infection symptoms and monitoring blood counts during treatment. [2]", [brukinsaInteraction, brukinsaSafety], null),
  fixture("invented_interaction_specific_event", "Moderate or strong CYP3A inhibitors increase the risk of bleeding from BRUKINSA. [1] [2]", [brukinsaInteraction, brukinsaSafety], { excerpt: "increase the risk of bleeding", reason: "The interaction source supports toxicity risk generally, not this specific adverse event." }),
  fixture("coadministration_condition_preserved", "If NUBEQA is used with combined P-gp and strong CYP3A4 inhibitors, the label calls for checking more often for NUBEQA adverse reactions. [1]", [nubeqaInteraction], null),
  fixture("coadministration_condition_lost", "The label calls for checking more often for adverse reactions in all NUBEQA patients. [1]", [nubeqaInteraction], { excerpt: "in all NUBEQA patients", reason: "The source limits the instruction to coadministration with combined P-gp and strong CYP3A4 inhibitors." }),
  fixture("unsupported_absence_of_checklist", "The label does not name a special interaction-specific toxicity checklist. [1]", [nubeqaInteraction], { excerpt: "does not name a special interaction-specific toxicity checklist", reason: "Omission from this excerpt does not establish absence from the label." }),
  fixture("unwarranted_monitoring_sequence", "After dose reduction for a CYP3A inhibitor, monitoring then follows general BRUKINSA safety guidance. [1] [2]", [brukinsaInteraction, brukinsaSafety], { excerpt: "monitoring then follows general BRUKINSA safety guidance", reason: "The sources do not define this interaction-specific monitoring sequence." }),
  fixture("explicitly_supported_scoped_absence", "Table 17 gives interaction effects and management instructions without incidence rates for individual adverse reactions attributable to these combinations. [1]", [brukinsaInteraction], null),
];
